Initial Pipeline Merge
Pipeline merge in

diff --git a/.github/workflows/setup.yml b/.github/workflows/setup.yml
--- a/.github/workflows/setup.yml
+++ b/.github/workflows/setup.yml
@@ -15,14 +15,67 @@ on:
       - .github/workflows/setup.yml
   workflow_dispatch:
 
+env:
+  FOLDER_PATH: "governance/"
+
 jobs:
-  GovernanceCI:
+  TerraformPrereqs:
     runs-on: ubuntu-latest
     
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
-      
-      - uses: hashicorp/setup-terraform@v1
+
+      - name: Build Bicep Templates
+        uses: azure/CLI@v1
         with:
-          terraform_wrapper: false
+          azcliversion: 2.27.2
+          inlineScript: |
+            cd ${{ env.FOLDER_PATH }}
+            for template in *.bicep; do
+              [ -f "$template" ] || break
+              echo "Building $template"
+              az bicep build --file $template
+            done
+        
+      - name: Run Checkov Tests
+        run: |
+          #!/bin/bash -ex
+          docker run -t -v $GITHUB_WORKSPACE/governance:/arm bridgecrew/checkov -d /arm --framework arm --soft-fail --output junitxml > junit_report.xml
+          # Remove ASCII Colour Encoding Characters
+          cat junit_report.xml | perl -pe 's/\x1b\[[^m]+m//g;' > formatted_report.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v2
+        if: always() # always run even if the previous step fails
+        with:
+          report_paths: 'formatted_report.xml'
+
+      - name: Publish Artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: governance-${{ github.job }}-${{ github.run_number }}
+          path: ${{ env.FOLDER_PATH }}
+
+  PlaygroundDeploy:
+    if: ${{ github.ref == 'refs/heads/main' }}
+    runs-on: ubuntu-latest
+    needs: TerraformPrereqs
+    environment:
+      name: Playground
+    steps:
+      - name: Download Artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: governance-${{ github.job }}-${{ github.run_number }}
+
+      - name: Azure Login
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+      - name: Deploy Resource Group
+        uses: azure/arm-deploy@v1
+        with:
+          scope: 'subscription'
+          template: 'resource-group.json'
